name: Build and package the Mac version

on:
  push:
    tags:
      - v*

jobs:
  build-app:
    name: Build for Mac
    runs-on: macos-13
    env:
      PYTHONVERSION: "3.11.0"
      MACOSX_DEPLOYMENT_TARGET: "13.0"

    steps:
    - uses: actions/checkout@v2

    - name: Cache Python download
      id: cache-python-download
      uses: actions/cache@v3
      with:
        path: ~/python.pkg
        key: macOS-Python-${{ env.PYTHON_VERSION }}

    - name: Get Python
      run: |
       curl https://www.python.org/ftp/python/${PYTHONVERSION}/python-${PYTHONVERSION}-macos11.pkg -o ~/python.pkg

    - name: Install Python
      run: sudo installer -pkg ~/python.pkg -target /

    - name: Install Python dependencies and build
      run: |
        python3 --version
        pip3 install --upgrade pip
        pip3 install -r requirements.txt
        brew install ccache
        chmod +x ./build_macos.sh
        ./build_macos.sh
        zip SalveTest.zip SalveTest.app -r

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.TOKEN }}
        file: SalveTest.zip
        asset_name: SalveTest.zip
        tag: ${{ github.ref }}
        overwrite: true
